# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxDataSource_Practice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxDataSource_Practice

	pod 'RxDataSources'
  pod 'RxSwift'
  pod 'RxCocoa'
 
 # pod 'Differentiator'	

	pod 'Then'
	pod 'SnapKit'
end
